### ISSUE TITLE
Add RPM package or Flatpak

### ISSUE THREAD

**Issue by Linux-Is-Best** [amir1376/ab-download-manager#175]
It would be great if there was either an RPM package (Fedora, openSUSE), or as an alternative, a Flatpak.  The benefit of a flatpak would be it could run on both RPM or DEB based system.  A lot of Linux developers tend to go the flatpak route for that reason. 

My reasoning for this request is a lot of folks, I know, have been moving away from Debian-based Linux distributions (disclosure, myself, included).  But would like to use your download manager.

Either solution would be great.

**Comment by amir1376** [comment]
why you are  not using  the installation script ?

**Comment by amanullahmenjli** [comment]
> why you are not using the installation script ?

One of the main advantages of using Linux distros is having all installed programs managed by a package manager (or two if you use flatpak too) which facilitates keeping everything organized and regularly updated.

**Comment by amir1376** [comment]
I'm planning to add an auto update feature to the app (which you may saw that in apps like discord postman etc...)
for this to work I need to have write access to the installation directory because of that I may not be able to add rpm package and remove the  deb package too.
instead can improve that installation script until then

**Comment by amanullahmenjli** [comment]
I think making auto updates optional and allowing the app to be available at least of flathub would be a better solution for linux users.
I personally don't like when apps try to manage their own updates and prefer to let that job for my package manager or for flatpak.

**Comment by amanullahmenjli** [comment]
If you don't want to publish it yourself for flathub would it be fine if I do it as a contributor so it can be labeled as officially published by the app devs on flathub?

**Comment by amir1376** [comment]
> I think making auto updates optional and allowing the app to be available at least of flathub would be a better solution for linux users. I personally don't like when apps try to manage their own updates and prefer to let that job for my package manager or for flatpak.

Of course I will make this optional. you can manually upgrade it using a script.

Unfortunately I don't know much about the `flathub` you mentioned. 
and I don't know if it may causes problem later or not.

For example 
I plan to add `Native Messaging` feature later to allow browsers to wake up the app when its not running. 
this feature needs an executable inside the app's directory (which I know that AppImage does not support this thing)

**Comment by amanullahmenjli** [comment]
> Of course I will make this optional. you can manually upgrade it using a script.

That's great to hear.

> Unfortunately I don't know much about the `flathub` you mentioned. and I don't know if it may causes problem later or not.

[Flathub](https://flathub.org/) is a store or repository that [flatpak](https://flatpak.org/) users can get software from. I'm not sure if flatpak can cause issues or not but I'll try to build this project on my machine with flatpak and see if it can cause any issues then report how it goes here.
 
> For example I plan to add `Native Messaging` feature later to allow browsers to wake up the app when its not running. this feature needs an executable inside the app's directory (which I know that AppImage does not support this thing)

Can you tell me more about how this feature is going to work?

**Comment by amir1376** [comment]
> Can you tell me more about how this feature is going to work?

You can read more about Native Messaging [here](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Native_messaging)

but in short it requires a file to be exists in installation folder and browser can execute it for communication.
for example 

```
───app
    \───bin
     |    \───ABDownloadManager (for now we have only this)
     |    \───ABDownloadManager_NativeMassagingHost
     |    \─── ....
     \...
```

app (and external apps like browsers) requires to have at least read only access to its installation directory. if its converted to a single executable binary (AppImage) then it may not support some features later.

**Comment by sabamdarif** [comment]
> why you are not using the installation script ?

yes the installer is ok but the problem is this depend on the our system library form that sometime it failed to launch like the the newer version i have crash issue the app don't launch for me anymore like this :- https://github.com/amir1376/ab-download-manager/issues/364 sure it because i might messed up something on my system, so if we have flatpak it will never happen and no need for any extra distro specific packaging also it will be easy to update, 

for the auto update option if it's linux (flatpak) it will only show the notification else for for other system it show update also there will be update now button (which will be not for linux/flatpak).

**Comment by gallium-stanza** [comment]
+1, Flatpak package is WAY better than installation script.
it's easier, safer, cleaner...
and it would enhance application discoverability when published to flathub, users often search the website or via clients (such as Gnome Software) for the software they need.

**Comment by Thundercup** [comment]
+1, flatpak is needed for linux version

**Comment by alsaghir** [comment]
Initial attempt (took two days) to make flatpak release works on Fedora KDE Plasma Desktop 42 was by the following config and successfuly installed and run. However, as this is a first, I am not confidence it is fully compliant with [flathub guidelines](https://docs.flathub.org/docs/for-app-authors/submission#submission-pr) (they are not few).

in a new folder

- io.github.amir1376.ab_download_manager.yml

```yml
# Use this manifest for your Flathub submission
app-id: io.github.amir1376.ab_download_manager
runtime: org.freedesktop.Platform
runtime-version: '25.08'
sdk: org.freedesktop.Sdk
command: ab-download-manager-wrapper.sh
sdk-extensions:
  - org.freedesktop.Sdk.Extension.openjdk

finish-args:
  - --share=network
  - --share=ipc
  - --socket=x11
  - --socket=fallback-x11
  - --socket=session-bus
  - --device=dri
  - --filesystem=xdg-download:create
  - --talk-name=org.freedesktop.Notifications
  - --talk-name=org.kde.StatusNotifierWatcher
  - --env=_JAVA_OPTIONS=-Djava.awt.headless=false -Dawt.toolkit.name=XToolkit
  - --env=PATH=/app/bin:/usr/bin:/app/lib/runtime/lib
  - --env=SKIKO_RENDER_API=SOFTWARE_FAST
  - --unset-env=WAYLAND_DISPLAY
 

modules:
  - name: openjdk
    buildsystem: simple
    build-commands:
      - /usr/lib/sdk/openjdk/install.sh
  - name: ab-download-manager
    buildsystem: simple
    build-commands:
      - install -D bin/ABDownloadManager /app/bin/ABDownloadManager
      - cp -r lib /app/
      - install -D ab-download-manager-wrapper.sh /app/bin/ab-download-manager-wrapper.sh
      - install -D io.github.amir1376.ab_download_manager.desktop /app/share/applications/io.github.amir1376.ab_download_manager.desktop
      - install -D io.github.amir1376.ab_download_manager.metainfo.xml /app/share/metainfo/io.github.amir1376.ab_download_manager.metainfo.xml
      - install -D io.github.amir1376.ab_download_manager.png /app/share/icons/hicolor/scalable/apps/io.github.amir1376.ab_download_manager.png
    sources:
      # Using your updated source file
      - type: archive
        url: https://github.com/amir1376/ab-download-manager/releases/download/v1.6.13/ABDownloadManager_1.6.13_linux_x64.tar.gz
        sha256: 6ea29c3a94cb8a2a650496af8d7f0920bf765c09710d23d7b7d86f41b3c3200b
        strip-components: 1
      
      # Your local files
      - type: file
        path: ab-download-manager-wrapper.sh
      - type: file
        path: io.github.amir1376.ab_download_manager.desktop
      - type: file
        path: io.github.amir1376.ab_download_manager.metainfo.xml
      - type: file
        path: io.github.amir1376.ab_download_manager.png
```

- io.github.amir1376.ab_download_manager.png (included in the .tar.gz binary inside lib folder)
- io.github.amir1376.ab_download_manager.metainfo.xml

```xml
<?xml version="1.0" encoding="UTF-8"?>
<component type="desktop-application">
  <id>io.github.amir1376.ab_download_manager</id>
  <name>AB Download Manager</name>
  <summary>A simple and efficient download manager</summary>
  <metadata_license>CC0-1.0</metadata_license>
  <project_license>MIT</project_license>
  <description>
    <p>
      AB Download Manager is a download manager built with Kotlin Multiplatform that helps you download files from the internet with ease.
    </p>
  </description>
  <launchable type="desktop-id">io.github.amir1376.ab_download_manager.desktop</launchable>
  <screenshots>
    <screenshot type="default">
      <caption>The main window of AB Download Manager</caption>
      <image>https://raw.githubusercontent.com/amir1376/ab-download-manager/master/assets/screenshots/app-home_dark.png</image>
    </screenshot>
  </screenshots>
  <releases>
    <release version="1.0.0" date="2023-10-27"/>
  </releases>
  <content_rating type="oars-1.1" />
  <url type="homepage">https://github.com/amir1376/ab-download-manager</url>
  <url type="bugtracker">https://github.com/amir1376/ab-download-manager/issues</url>
  <developer_name>Amir</developer_name>
</component>
```

- io.github.amir1376.ab_download_manager.desktop

```
[Desktop Entry]
Name=AB Download Manager
Comment=A simple and efficient download manager
Exec=ab-download-manager-wrapper.sh
Icon=io.github.amir1376.ab_download_manager
Type=Application
Categories=Network;FileTransfer;
```

- ab-download-manager-wrapper.sh

```sh
#!/bin/bash

# Force the Java environment to use the correct graphical settings
# export _JAVA_OPTIONS="-Djava.awt.headless=false -Dawt.toolkit.name=XToolkit"
# export _JAVA_OPTIONS="-Djava.awt.headless=false -Dawt.toolkit.name=XToolkit -Dawt.toolkit=sun.awt.X11.XToolkit -Dsun.java2d.xrender=false"
export _JAVA_OPTIONS="-Djava.awt.headless=false -Dawt.toolkit.name=XToolkit"

# Use 'exec' to replace the script process with the actual application process.
# This runs the original binary that you packaged.
exec /app/bin/ABDownloadManager "$@"
```

Use the following commands to install and run after

```sh
# install the builder
flatpak remote-add --if-not-exists --user flathub https://dl.flathub.org/repo/flathub.flatpakrepo
flatpak install -y flathub org.flatpak.Builder

# Build
flatpak run --command=flathub-build org.flatpak.Builder --repo=repo io.github.amir1376.ab_download_manager.yml

# Install
flatpak --user install io.github.amir1376.ab_download_manager -y
# or update if previously installed and wanted to try your modifications
flatpak --user update io.github.amir1376.ab_download_manager -y

# Run
flatpak run -v io.github.amir1376.ab_download_manager
```

By no means this is a clean or final version, it is just first attempt to make it run successfully. Tray icon is not working yet, wayland is not supported and there are redundant configurations like _JAVA_OPTIONS in the yaml and sh wrapper.
